/* ── Training Data — Programa Feminino v2.2 ───────────────── */
const RIR_OPTS = [
  { label: 'RIR 4+', sub: 'Muito fácil', cls: 'sel-easy', color: '#1E7145' },
  { label: 'RIR 3',  sub: 'Fácil',       cls: 'sel-easy', color: '#2E9E5B' },
  { label: 'RIR 2',  sub: 'Moderado',    cls: 'sel-mod',  color: '#C85A00' },
  { label: 'RIR 1',  sub: 'Difícil',     cls: 'sel-hard', color: '#8B2313' },
  { label: 'RIR 0',  sub: 'Falha',       cls: 'sel-max',  color: '#3D0800' },
];

const DAYS = [
  /* ── SEGUNDA ─────────────────────────────────────────────── */
  {
    key: 'seg', label: 'Segunda', full: 'Segunda-feira',
    theme: '#8B1A4A', subtitle: 'Funcional / Core / Glúteo',
    items: [
      { type:'ex', name:'Agachamento Goblet com Halter',
        biset: false, priority: false,
        phases:['4x12 · Halter 8–12kg · Foco técnico','4x15 · Halter 12–16kg · Desça 3s','5x15 · Halter pesado · Pausa 1s embaixo'],
        instrucoes:'FASE 1–2 — Goblet Squat: segure um halter com as duas mãos na frente do peito (posição "cálice"). Pés na largura dos ombros, pontas levemente abertas. Desça até quebrar 90° — o peso frontal força o tronco ereto e protege a lombar. FASE 3 — pode progredir para halter muito pesado ou barra leve. Coluna SEMPRE neutra. Glúteos e quadríceps como motores principais.',
        nota:'🔄 Substitui o agachamento livre com halteres nas laterais, que força o tronco a inclinar para frente. Goblet é mais seguro e mais eficaz para quem está consolidando o padrão de movimento.' },
      { type:'ex', name:'Prancha Frontal no Solo + Variação',
        biset: false, priority: false,
        phases:['4x 45s · Posição clássica no antebraço','4x 60s + 5 elevações de braço alternadas','5x 75s + 10 toques de ombro'],
        instrucoes:'Antebraço no solo, quadril neutro, glúteos contraídos, abdômen firme. NÃO deixe a lombar cair — se cair antes do tempo, pare. Qualidade acima de duração. Nas Fases 2 e 3, as variações de desequilíbrio (braço elevado, toque de ombro) recrutam oblíquos e estabilizadores profundos.',
        nota:'✅ Mantido. Progressão adequada. Variações nas Fases 2 e 3 adicionadas para aumentar o estímulo de core sem prolongar o tempo de prancha indefinidamente.' },
      { type:'ex', name:'Subida no Caixote com Halteres (Step-Up)',
        biset: false, priority: false,
        phases:['4x10 cada perna · Caixote 30–40cm · Sem peso','4x12 cada perna · Halteres 4–6kg','5x12 cada perna · Halteres 8–12kg · Joelho drive no topo'],
        instrucoes:'Apoie o pé INTEIRO no caixote. Suba empurrando EXCLUSIVAMENTE pela perna de cima — sem impulso da perna de baixo. No topo, eleve o joelho da perna livre até a cintura (joelho drive) para recrutar mais glúteo. Desça de forma controlada (2–3s). Na Fase 1 sem peso para consolidar o padrão.',
        nota:'✅ Mantido. "Joelho drive" no topo adicionado para aumentar recrutamento de glúteo máximo.' },
      { type:'ex', name:'Prancha Lateral + Elevação de Quadril (Hip Dip)',
        biset: false, priority: false,
        phases:['4x 30s cada lado · Antebraço no solo','4x 45s + 8 elevações de quadril cada lado','5x 60s + 12 elevações · abdução opcional'],
        instrucoes:'Corpo em linha reta, apoiado no antebraço no solo. Quadril elevado, não deixe cair. Na Fase 2/3: adicione o Hip Dip — desça o quadril até quase tocar o chão e suba de volta 8–12 vezes. Recruta oblíquo e glúteo médio simultaneamente.',
        nota:'🔄 UPGRADE: Progressão com Hip Dip nas Fases 2 e 3 dobra o estímulo de glúteo médio e oblíquo.' },
      { type:'ex', name:'Polichinelo com Salto Controlado',
        biset: false, priority: false,
        phases:['4x 45s · Salto BAIXO e controlado · Aterrissagem suave','4x 60s · Salto moderado · Ritmo constante','5x 60s · Ritmo máximo sustentado'],
        instrucoes:'FASE 1: salto baixo (5–10cm), joelhos levemente dobrados na aterrissagem — nunca joelhos travados. O objetivo é manter o ritmo e elevar a FC, NÃO a altura do salto. FASE 2/3: aumente a explosividade mantendo a aterrissagem suave. Se sentir dor nos joelhos, retorne à versão de Fase 1.',
        nota:'🔄 AJUSTE DE SEGURANÇA: "Salte ao limite" na Fase 1 é instrução de risco. Salto controlado e baixo eleva igualmente a FC sem sobrecarregar joelhos e tornozelos.' },
      { type:'stretch', name:'Postura da Criança', presc:'45s — Ajoelhe, estenda os braços à frente e afunde o tronco.' },
      { type:'stretch', name:'Alongamento de Quadril', presc:'45s cada lado — Em fenda baixa, mantenha o quadril pressionado para baixo.' },
      { type:'stretch', name:'Alongamento de Lombar', presc:'45s — Deitado de costas, abrace os joelhos em direção ao peito.' },
      { type:'stretch', name:'Piriforme deitado', presc:'30s cada lado — Deitado, cruce uma perna e puxe o joelho ao peito.' },
      { type:'stretch', name:'Panturrilha na parede', presc:'30s cada pé — Calcanhar no chão, pé na parede, empurre o quadril à frente.' },
    ],
  },

  /* ── TERÇA ───────────────────────────────────────────────── */
  {
    key: 'ter', label: 'Terça', full: 'Terça-feira',
    theme: '#6A1B6E', subtitle: 'Membros Inferiores + Glúteos (Bi-Sets)',
    items: [
      { type:'ex', name:'BI-SET 1A · Leg Press 45°',
        biset: true, priority: false,
        phases:['4x10 · Carga alta · 2s descida','4x10 · Carga máxima · Tempo sob tensão','4x12 · Carga máxima + Drop-set na última'],
        instrucoes:'Pés na largura dos ombros, posição média na plataforma. Desça até 90° SEM deixar o lombar sair do assento. Não trave os joelhos no topo. Fase excêntrica de 2–3s (descida lenta). Ao terminar, vá DIRETO para a Extensora sem descansar.',
        nota:'✅ Mantido. Ênfase na fase excêntrica adicionada — dobra o tempo sob tensão sem aumentar a carga.' },
      { type:'ex', name:'BI-SET 1B · Cadeira Extensora',
        biset: true, priority: false,
        phases:['4x12 · Carga moderada · 1s isométrico no topo','4x12 · Carga alta · 1s isométrico','4x10 + Drop-set · Unilateral opcional'],
        instrucoes:'Execute LOGO APÓS o Leg Press, sem descansar. Estenda os joelhos completamente espremendo o quadríceps por 1s no topo. Retorne em 3s (excêntrica lenta). Descanso de 45s somente após completar o bi-set. ATENÇÃO: contraindicada se houver condromalácia patelar.',
        nota:'✅ Mantido. Isométrico de 1s no topo e instrução de contraindicação adicionados.' },
      { type:'ex', name:'BI-SET 2A · Hip Thrust com Barra no Banco ★',
        biset: true, priority: true,
        phases:['4x12 · Peso corporal ou barra leve · 2s isométrico','4x10 · Barra moderada · 2s isométrico no topo','4x12 · Carga máxima + 2s isométrico'],
        instrucoes:'★ EXERCÍCIO PRIORITÁRIO PARA GLÚTEOS. Escápula apoiada no banco, pés no chão, joelhos a 90°. Barra sobre os quadris com proteção (toalha/pad). Empurre o quadril para CIMA até extensão total — quadril, joelhos e ombros em linha. Segure 2s no topo espremendo os glúteos ao máximo. NÃO hiperesstenda a lombar. Vá DIRETO para a Cadeira Flexora.',
        nota:'🔄 UPGRADE CRÍTICO: Hip Thrust com barra NO BANCO substitui a Elevação Pélvica no chão. Recruta 3x mais glúteo máximo (Contreras et al., 2015). Mudança mais importante do programa.' },
      { type:'ex', name:'BI-SET 2B · Cadeira Flexora Sentada (Isquiotibiais)',
        biset: true, priority: false,
        phases:['4x10 · Carga moderada · Sentada','4x10 · Carga alta · Sentada','4x12 · Carga máxima · 2s isométrico no pico'],
        instrucoes:'Execute LOGO APÓS o Hip Thrust, sem descansar. Puxe o rolo em direção ao banco espremendo a coxa. VERSÃO SENTADA obrigatória — menor risco de tendinopatia proximal vs. deitada. Na Fase 3 mantenha 2s no pico antes de soltar. Descanso de 45s após o bi-set.',
        nota:'🔄 AJUSTE: Versão sentada especificada. Reduz risco de tendinopatia proximal — especialmente relevante para 45 anos.' },
      { type:'ex', name:'BI-SET 3A · Stiff com Halteres',
        biset: true, priority: false,
        phases:['4x10 · Carga moderada · Coluna neutra','4x10 · Carga alta · Excêntrica 3s','4x12 · Carga máxima + pausa 1s no ponto mais baixo'],
        instrucoes:'Pés na largura do quadril, joelhos LEVEMENTE flexionados (não travar). Incline o tronco à frente empurrando o QUADRIL para trás — é uma "dobradiça de quadril", não uma flexão de tronco. Halteres descem raspando nas coxas com COLUNA NEUTRA — NUNCA arredondar a lombar (causa lesão). Sinta o posterior de coxa e glúteo alongar. Vá DIRETO para a Abdutora.',
        nota:'🔄 INSTRUÇÃO REVISADA: Coluna neutra e padrão de dobradiça de quadril adicionados. Lombar arredondada no stiff é a principal causa de lesão neste exercício.' },
      { type:'ex', name:'BI-SET 3B · Cadeira Abdutora (Glúteo Médio)',
        biset: true, priority: false,
        phases:['4x15 · Carga moderada · Tronco levemente inclinado','4x15 · Carga alta · Tronco inclinado','4x12 · Carga máxima · Tronco inclinado'],
        instrucoes:'Execute LOGO APÓS o Stiff, sem descansar. INCLINE o tronco levemente para a frente (15–20°) — isso muda o ângulo de recrutamento para a porção superior e lateral do glúteo médio, que cria o formato arredondado. Empurre para fora de forma controlada. Descanso de 45s após o bi-set.',
        nota:'✅ Mantido. Instrução de inclinação do tronco reforçada — é o que diferencia um exercício estético de um mecânico.' },
      { type:'ex', name:'Panturrilha em Pé na Máquina',
        biset: false, priority: false,
        phases:['4x15 · Carga alta · Amplitude total','4x15 · Carga máxima · Excêntrica 2s','4x20 · Carga máxima + pausa 1s no topo'],
        instrucoes:'Amplitude TOTAL obrigatória: calcanhar desce abaixo do nível do degrau na excêntrica, sobe até a máxima extensão na concêntrica. Meio movimento não estimula o sóleo adequadamente. Controle a descida em 2s.',
        nota:'✅ Mantido. Instrução de amplitude total reforçada — erro mais comum neste exercício.' },
      { type:'stretch', name:'Tronco inclinado para frente (pernas esticadas)', presc:'45s — Sentada, pernas esticadas, incline o tronco à frente mantendo a coluna alongada.' },
      { type:'stretch', name:'Fenda baixa (isquiotibiais + quadril)', presc:'30s cada lado — Fenda profunda com joelho traseiro no chão.' },
      { type:'stretch', name:'Piriforme em posição deitada', presc:'45s — Deitada, cruce a perna sobre a outra e puxe o joelho ao peito.' },
      { type:'stretch', name:'Panturrilha na parede', presc:'45s cada pé.' },
    ],
  },

  /* ── QUARTA ──────────────────────────────────────────────── */
  {
    key: 'qua', label: 'Quarta', full: 'Quarta-feira',
    theme: '#8B2313', subtitle: 'Metabólico HIIT + Circuito',
    items: [
      { type:'ex', name:'HIIT — Esteira Inclinada ou Elíptico',
        biset: false, priority: false,
        phases:['4 blocos: 40s esforço / 20s recuperação','4 blocos: 45s esforço / 15s recuperação','5 blocos: 50s esforço / 10s recuperação'],
        instrucoes:'PREFERENCIAL: Elíptico ou Bike ergométrica — zero impacto articular, mesmo EPOC. Se usar esteira: aumente a INCLINAÇÃO (10–14%) em vez da velocidade. NÃO correr em velocidade máxima com impacto repetido. Warm-up de 3 min plano antes. Resfriamento de 2 min no final. Meta de FC: 80–90% do máximo (~140–157bpm para 45 anos).',
        nota:'🔄 AJUSTE: Mínimo de 4 blocos desde a Fase 1 (original tinha 3). Elíptico/bike como preferencial adicionado — protocolo de inclinação na esteira é mais seguro que corrida em velocidade máxima.' },
      { type:'ex', name:'Meio-Burpee (Sprawl) no Banco ou Solo',
        biset: false, priority: false,
        phases:['3 voltas: 40s · Banco (mãos elevadas)','4 voltas: 50s · Banco ou solo','5 voltas: 55s · Solo completo'],
        instrucoes:'FASE 1: mãos no banco — agache, apoie as mãos, jogue as pernas para trás (prancha), traga de volta e levante. SEM SALTO. FASES 2/3: progrida para o solo conforme ganho de condicionamento. Ritmo controlado — não perca a postura no cansaço.',
        nota:'🔄 PROGRESSÃO: Banco na Fase 1 → solo nas Fases 2/3. Instrução original mandava ao solo desde o início sem progressão gradual.' },
      { type:'ex', name:'Kettlebell Swing (Dobradiça de Quadril)',
        biset: false, priority: false,
        phases:['3 voltas: 40s · KB 8–10kg · Dominar o padrão','4 voltas: 50s · KB 12kg · Se técnica sólida','5 voltas: 55s · KB 14–16kg · Ritmo intenso'],
        instrucoes:'O swing é gerado EXCLUSIVAMENTE pela articulação do quadril — NÃO é agachamento nem levantamento de braços. Joelhos levemente dobrados, empurre o quadril para trás deixando o KB descer entre as pernas como pêndulo, depois dispare os quadris para frente explosivamente. O KB sobe por inércia. Abdômen firme o tempo todo.',
        nota:'✅ Mantido. Instrução técnica ampliada com ênfase no padrão de dobradiça.' },
      { type:'ex', name:'Abdominal Bicicleta (Bicycle Crunch) ★',
        biset: false, priority: false,
        phases:['3 voltas: 40s · Ritmo CONTROLADO','4 voltas: 50s · Ritmo moderado','5 voltas: 55s · Ritmo controlado'],
        instrucoes:'Deitada de costas, mãos ATRÁS da cabeça (sem puxar o pescoço). Suba o ombro DIREITO em direção ao joelho ESQUERDO enquanto estende a perna direita. Alterne de forma CONTROLADA — velocidade NÃO é o objetivo. Ativação 2,5x maior de oblíquos vs. abdominal remador (ACE, 2001). NÃO balance o pescoço.',
        nota:'🔄 SUBSTITUIÇÃO: Abdominal Remador com técnica "explosivo abraçando os joelhos" tem alto risco de compensação cervical. Bicycle Crunch é superior em ativação e mais seguro.' },
      { type:'ex', name:'Corrida Estacionária com Joelhos Altos',
        biset: false, priority: false,
        phases:['3 voltas: 40s ativo','4 voltas: 50s ativo','5 voltas: 55s + sprint final 10s'],
        instrucoes:'Corra no lugar elevando os joelhos até a linha da cintura. Braços acompanham o movimento como na corrida real. Mantenha o tronco ereto — não se curve para frente. Termine com 3 min de caminhada leve para recuperação gradual da FC.',
        nota:'✅ Mantido. Instrução de postura adicionada. Sprint final de 10s na Fase 3 como finalizador metabólico.' },
      { type:'stretch', name:'Isquiotibiais sentada', presc:'1 min — Sentada com pernas esticadas, incline o tronco à frente.' },
      { type:'stretch', name:'Lombar (abraço de joelhos)', presc:'45s — Deitada, abrace os dois joelhos contra o peito.' },
      { type:'stretch', name:'Mobilização de quadril em fenda', presc:'30s cada lado — Fenda profunda, joelho traseiro no chão, empurre o quadril à frente.' },
      { type:'stretch', name:'Flexores do quadril', presc:'45s cada lado — Joelho traseiro no chão, pélvis neutra, sinta o alongamento na frente da coxa.' },
      { type:'stretch', name:'Cat-Cow (mobilidade lombar)', presc:'30s — De quatro apoios, arqueie e curve a coluna alternadamente.' },
    ],
  },

  /* ── QUINTA ──────────────────────────────────────────────── */
  {
    key: 'qui', label: 'Quinta', full: 'Quinta-feira',
    theme: '#2E6DA4', subtitle: 'Membros Superiores (Bi-Sets)',
    items: [
      { type:'ex', name:'BI-SET 1A · Puxada no Pulley Aberto',
        biset: true, priority: false,
        phases:['4x10 · Agarre largo pronado','4x10 · Mais carga · 2s isométrico','4x12 · Descida lenta 4s · Agarre neutro opcional'],
        instrucoes:'Incline levemente o tronco (~15°). Puxe a barra até a altura do queixo/clavícula FECHANDO as escápulas. Na Fase 3: alterne para agarre neutro (paralelo) para reduzir estresse no manguito rotador. Controle a excêntrica (4s de volta). Vá DIRETO para o Supino.',
        nota:'✅ Mantido. Ênfase excêntrica e variação de agarre na Fase 3 adicionadas.' },
      { type:'ex', name:'BI-SET 1B · Supino Inclinado na Máquina (30–45°)',
        biset: true, priority: false,
        phases:['4x10 · Carga moderada','4x10 · Mais carga','4x12 · Carga máxima + pausa 1s no pico'],
        instrucoes:'INCLINADO (30–45°) preferencial ao plano — recruta mais peitoral superior e reduz carga no manguito rotador. Ombros RETRAÍDOS e DEPRIMIDOS durante todo o movimento. Execute LOGO APÓS a Puxada, sem descansar. Descanso de 45s após o bi-set.',
        nota:'🔄 AJUSTE: Supino inclinado substitui o plano — mais seguro para o ombro pós-40.' },
      { type:'ex', name:'BI-SET 2A · Desenvolvimento com Halteres',
        biset: true, priority: false,
        phases:['4x10 · Halteres leves · Cotovelos a 90°','4x8 · Mais carga','4x10 · Carga máxima + 8 elevações laterais leves'],
        instrucoes:'Sentada com apoio nas costas. Halteres permitem trajetória anatômica natural — mais seguro que máquina para o manguito rotador. Cotovelos a 90° no início. Empurre os halteres para cima sem juntar completamente no topo. NUNCA além do ponto de dor. Fase 3: 8 elevações laterais leves após cada série.',
        nota:'🔄 AJUSTE: Halteres como preferência sobre máquina. Trajetória livre protege o manguito rotador.' },
      { type:'ex', name:'BI-SET 2B · Remada Triângulo no Cabo',
        biset: true, priority: false,
        phases:['4x10 · Carga moderada','4x10 · Mesma carga','4x12 · Segurar 2s no peito · Carga máxima'],
        instrucoes:'Execute LOGO APÓS o Desenvolvimento, sem descansar. Puxe o triângulo espremendo as costas — cotovelos passam pela lateral do tronco. Na Fase 3 mantenha 2s com o triângulo no peito para isométrico. Descanso de 45s após o bi-set.',
        nota:'✅ Mantido. Isométrico de 2s na Fase 3 adicionado para maior ativação de dorsal.' },
      { type:'ex', name:'BI-SET 3A · Elevação Lateral com Halteres',
        biset: true, priority: false,
        phases:['4x12 · Carga moderada · Cotovelos levemente dobrados','4x10 · Carga alta','4x12 · Carga máxima'],
        instrucoes:'Em pé, cotovelos levemente dobrados (não travados). Eleve os halteres para os lados até a altura dos ombros — NÃO acima. Controle a descida (2s). Vá DIRETO para o Crucifixo Inverso.',
        nota:'✅ Mantido. Controle excêntrico adicionado.' },
      { type:'ex', name:'BI-SET 3B · Crucifixo Inverso na Máquina',
        biset: true, priority: false,
        phases:['4x12 · Carga moderada','4x10 · Carga alta','4x12 · Carga máxima · Descida controlada 3s'],
        instrucoes:'Sente de frente para o aparelho. Segure os apoios e empurre os braços para trás em arco, espremendo as costas superiores e o ombro posterior. Execute LOGO APÓS a Elevação Lateral. Descanso de 45s após o bi-set.',
        nota:'✅ Mantido. Excêntrica de 3s na Fase 3 adicionada.' },
      { type:'ex', name:'Super-Série: Tríceps Pulley + Rosca Direta',
        biset: true, priority: false,
        phases:['4x10 cada · Sem descanso entre os dois','4x10 cada · Carga progressiva','4x12 cada + Drop-set final · Carga máxima'],
        instrucoes:'Tríceps Pulley: cotovelos COLADOS ao corpo, empurre até extensão completa, retorne controlado. IMEDIATAMENTE: Rosca Direta com halteres, cotovelos estáticos, supinação total no topo. Descanso de 60–90s somente após o par. Drop-set na última série da Fase 3.',
        nota:'✅ Mantido. Drop-set na Fase 3 e instrução de cotovelos fixos adicionados.' },
      { type:'stretch', name:'Estiramento de bíceps e latíssimo', presc:'30s cada lado — Braço estendido na parede, gire levemente o tronco.' },
      { type:'stretch', name:'Peitoral na parede', presc:'45s cada lado — Mão na parede na altura do ombro, gire o tronco para longe.' },
      { type:'stretch', name:'Pendulares de ombro', presc:'45s — Incline o tronco, deixe o braço balançar livremente em círculos.' },
      { type:'stretch', name:'Rotação de tronco com braço estendido', presc:'30s cada lado — Deitada de costas, braço estendido, deixe o joelho cruzar o corpo.' },
      { type:'stretch', name:'Flexão e extensão passiva do cotovelo', presc:'30s cada braço — Mova suavemente o cotovelo em toda a amplitude.' },
    ],
  },

  /* ── SEXTA ───────────────────────────────────────────────── */
  {
    key: 'sex', label: 'Sexta', full: 'Sexta-feira',
    theme: '#C85A00', subtitle: 'Full Body Força + Core + Glúteo',
    items: [
      { type:'ex', name:'Agachamento 1½ Rep com Halter (Pausa)',
        biset: false, priority: false,
        phases:['4x12 · Halter moderado · 1½ rep completa','4x15 · Halter mais pesado','5x15 · Carga máxima'],
        instrucoes:'Segure um halter pesado no peito (posição Goblet). COMO EXECUTAR 1 REPETIÇÃO: (1) agache até abaixo de 90°, (2) suba até a METADE, (3) volte a descer até abaixo de 90°, (4) suba completamente — isso conta como 1 rep. O retorno ao meio cria uma "insistência" que dobra o tempo sob tensão no range de maior ativação de glúteo. Coluna neutra o tempo todo.',
        nota:'🔄 RENOMEADO E INSTRUÇÃO REVISADA: "Agachamento com Insistência" era ambíguo. "1½ Rep com Pausa" descreve exatamente o movimento. Execução passo a passo adicionada.' },
      { type:'ex', name:'Flexão de Braço no Solo (com Regressão)',
        biset: false, priority: false,
        phases:['4x8 · Com joelhos no chão se necessário · Ritmo lento','4x12 · Sem joelhos · Pausa 1s embaixo','5x12 · Sem joelhos · Descida lenta 3s'],
        instrucoes:'FASE 1: se não conseguir 8 reps completas com boa forma, use os joelhos — é a progressão correta. Mãos ligeiramente mais largas que os ombros, cotovelos a ~45° (não abertos a 90°). Desça até o peito quase tocar o chão. FASE 2/3: sem joelhos, adicione pausa de 1s no ponto mais baixo.',
        nota:'🔄 REGRESSÃO ADICIONADA: Progressão joelhos (F1) → sem joelhos (F2/3) é a abordagem correta.' },
      { type:'ex', name:'Passada Caminhando com Halteres (Walking Lunge)',
        biset: false, priority: false,
        phases:['4x20 passos · Afundo estático · Sem peso','4x24 passos · Halteres leves · Walking lunge','5x24 passos · Halteres mais pesados'],
        instrucoes:'FASE 1: afundo estático (no lugar) para aprender o padrão sem se preocupar com equilíbrio. FASES 2/3: walking lunge — cada passo à frente é uma rep. Tronco ereto, joelho da frente NÃO ultrapassa a ponta do pé, joelho de trás quase toca o chão.',
        nota:'🔄 PROGRESSÃO: Afundo estático (F1) → Walking Lunge (F2/3). Instrução original mandava walking lunge com carga desde o início.' },
      { type:'ex', name:'Hip Thrust Unilateral no Banco ★ NOVO',
        biset: false, priority: true,
        phases:['4x10 cada lado · Peso corporal','4x12 · Halter sobre o quadril · 2s isométrico','5x12 · Carga alta + 2s isométrico no topo'],
        instrucoes:'★ ADICIONADO para reforçar foco em glúteos na sexta. Escápula no banco, UMA perna estendida à frente, a outra no chão com joelho a 90°. Empurre com a perna no chão até extensão total. Segure 2s no topo espremendo o glúteo ao máximo. Unilateral identifica e corrige assimetrias — muito comum entre glúteo dominante e não-dominante.',
        nota:'➕ ADIÇÃO: Programa original não tinha exercício de glúteo na sexta. Hip Thrust unilateral fecha a semana com ênfase no objetivo principal.' },
      { type:'ex', name:'Abdominal Infra com Elevação de Quadril',
        biset: false, priority: false,
        phases:['4x15 · Joelhos dobrados · Eleva quadril no topo','4x20 · Pernas semi-estendidas','5x20 · Pernas estendidas + hip lift no topo'],
        instrucoes:'Deitada, mãos sob o quadril. Eleve as pernas e NO PONTO MAIS ALTO empurre o quadril para cima (hip lift). A elevação final ativa o reto inferior — sem ela é apenas elevação de pernas. Se sentir tensão lombar em vez do abdômen: dobre mais os joelhos.',
        nota:'🔄 UPGRADE: Hip lift no topo converte em Reverse Crunch completo. Instrução de segurança para tensão lombar adicionada.' },
      { type:'ex', name:'Mountain Climber (Alpinista) no Banco ou Solo',
        biset: false, priority: false,
        phases:['4x 30s · Banco (mãos elevadas) · Ritmo controlado','4x 45s · Solo · Ritmo moderado','5x 60s · Solo · Ritmo máximo'],
        instrucoes:'FASE 1: mãos no banco. FASES 2/3: mãos no solo. Na posição de prancha alta, puxe os joelhos em direção ao peito alternando rapidamente. Tronco firme, quadril NÃO deve subir. Finalizador metabólico da semana — mantenha 2 min de caminhada leve após.',
        nota:'🔄 PROGRESSÃO: Banco (F1) → solo (F2/3). Instrução de quadril firme adicionada.' },
      { type:'stretch', name:'Quadríceps em pé', presc:'45s cada perna — Em pé, puxe o tornozelo em direção ao glúteo.' },
      { type:'stretch', name:'Peitoral com braços cruzados', presc:'45s — Cruze um braço à frente do peito e pressione com o outro.' },
      { type:'stretch', name:'Piriforme deitado (Hip Thrust)', presc:'45s cada lado — Deitada, cruce a perna e puxe o joelho ao peito.' },
      { type:'stretch', name:'Flexores do quadril deitado', presc:'30s cada lado — Joelho traseiro no chão, pélvis neutra.' },
      { type:'stretch', name:'Respiração profunda diafragmática', presc:'2 min — Inspire pelo nariz em 4s, segure 2s, expire pela boca em 6s.' },
    ],
  },

  /* ── SÁBADO ──────────────────────────────────────────────── */
  {
    key: 'sab', label: 'Sábado', full: 'Sábado',
    theme: '#5D4037', subtitle: 'Flexibilidade e Recuperação Ativa',
    items: [
      { type:'ex', name:'Mobilidade Articular Ativa (10 min)',
        biset: false, priority: false,
        phases:['Círculos de quadril + ombros + tornozelos','Idem com maior amplitude','Idem com respiração diafragmática'],
        instrucoes:'Círculos lentos e amplos: tornozelo → joelho → quadril → coluna → ombro → pescoço. 10 repetições em cada direção. NÃO forçar dor — objetivo é lubrificação articular.',
        nota:'➕ ADICIONADO: Mobilidade ativa como início da sessão de sábado. Prepara as articulações para o alongamento estático e acelera a recuperação.' },
      { type:'ex', name:'Foam Roller — Auto-massagem Miofascial',
        biset: false, priority: false,
        phases:['10 min · Quadríceps, IT band, lombar, panturrilha','15 min · Idem + glúteos e dorsais','20 min · Protocolo completo full body'],
        instrucoes:'Posicione o rolo sob o músculo-alvo e deslize lentamente 10x. Nos pontos dolorosos ("nós"), mantenha 20–30s. NÃO rolar sobre articulações ou diretamente na coluna lombar.',
        nota:'➕ ADICIONADO: Padrão ouro de recuperação para 5 dias/semana com 45 anos.' },
      { type:'ex', name:'Alongamento Estático Completo (20–30 min)',
        biset: false, priority: false,
        phases:['20 min · Todos os grandes grupos musculares','25 min · Adicionar yoga simples','30 min · Protocolo completo + respiração'],
        instrucoes:'Sequência: (1) Isquiotibiais 60s · (2) Quadríceps 60s · (3) Glúteos/piriforme 60s · (4) Peitoral 60s · (5) Latíssimo 60s · (6) Flexores do quadril 60s · (7) Panturrilha 60s · (8) Lombar gato-vaca + postura da criança 60s. Respiração profunda em cada posição.',
        nota:'✅ Mantido. Foam roller e mobilidade adicionados como pré-sessão. Fase 2: yoga simples (Surya Namaskar) — excelente para mobilidade de quadril.' },
      { type:'ex', name:'Shavasana (relaxamento completo)',
        biset: false, priority: false,
        phases:['3 min · Deitada, olhos fechados','4 min · Com respiração diafragmática consciente','5 min · Protocolo completo'],
        instrucoes:'Deite-se de costas, pernas afastadas, braços ao lado com palmas para cima. Feche os olhos. Relaxe conscientemente cada parte do corpo da cabeça aos pés. Respire naturalmente.',
        nota:'➕ ADICIONADO: Finalizador da sessão de recuperação. Reduz cortisol e ativa o sistema nervoso parassimpático.' },
    ],
  },

  /* ── DOMINGO ─────────────────────────────────────────────── */
  {
    key: 'dom', label: 'Domingo', full: 'Domingo',
    theme: '#424242', subtitle: 'Descanso completo',
    isRest: true,
  },
];
